# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Proyek Sains Data
author: AHMAD MUFID RISQI
logo: logo.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/Mufid-031/PSD # Online location of your book
  path_to_book: proyek-sains-data # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

only_build_toc_files: true # only build TOC
